/*
  # Create Pre-made Collection Table

  1. New Tables
    - `Pre-made Collection`
      - `id` (bigint, primary key) - Unique identifier for each collection rug
      - `image` (text) - URL path to the rug image stored in Supabase Storage
      - `title` (text) - Name/title of the rug
      - `description` (text) - Description of the rug design
      - `price` (numeric) - Price of the rug in dollars
      - `stripe_price_id` (text) - Stripe price ID for payment processing
      - `stripe_prod_id` (text) - Stripe product ID for payment processing
      - `date_sold` (timestamptz, nullable) - Date when the rug was sold (null if not sold)
      - `is_available` (boolean) - Whether the rug is currently available for purchase
      - `created_at` (timestamptz) - Timestamp when the record was created
      - `updated_at` (timestamptz) - Timestamp when the record was last updated

  2. Security
    - Enable RLS on `Pre-made Collection` table
    - Add policy for anyone to view available collection rugs (public read access)
    - Add policy for authenticated users to insert collection rugs
    - Add policy for authenticated users to update collection rugs
    - Add policy for authenticated users to delete collection rugs

  3. Triggers
    - Auto-update `updated_at` timestamp on record updates
*/

-- Create the Pre-made Collection table
CREATE TABLE IF NOT EXISTS "Pre-made Collection" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  image text,
  title text,
  description text,
  price numeric(10, 2) CHECK (price >= 0),
  stripe_price_id text,
  stripe_prod_id text,
  date_sold timestamptz,
  is_available boolean DEFAULT true,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE "Pre-made Collection" ENABLE ROW LEVEL SECURITY;

-- Public can view all collection rugs
CREATE POLICY "Anyone can view collection rugs"
  ON "Pre-made Collection"
  FOR SELECT
  TO public
  USING (true);

-- Authenticated users can insert collection rugs
CREATE POLICY "Authenticated users can insert collection rugs"
  ON "Pre-made Collection"
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Authenticated users can update collection rugs
CREATE POLICY "Authenticated users can update collection rugs"
  ON "Pre-made Collection"
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Authenticated users can delete collection rugs
CREATE POLICY "Authenticated users can delete collection rugs"
  ON "Pre-made Collection"
  FOR DELETE
  TO authenticated
  USING (true);

-- Create trigger to automatically update updated_at
DROP TRIGGER IF EXISTS update_premade_collection_updated_at ON "Pre-made Collection";
CREATE TRIGGER update_premade_collection_updated_at
  BEFORE UPDATE ON "Pre-made Collection"
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
