/*
  # Duplicate Pre-made Collection as Pre-made Rugs

  1. New Tables
    - `Pre-made Rugs`
      - `id` (bigint, primary key) - Unique identifier for each rug
      - `image` (text) - URL path to the rug image stored in Supabase Storage
      - `title` (text) - Name/title of the rug
      - `description` (text) - Description of the rug design
      - `price` (numeric) - Price of the rug in dollars
      - `stripe_price_id` (text) - Stripe price ID for payment processing
      - `stripe_prod_id` (text) - Stripe product ID for payment processing
      - `date_sold` (timestamptz, nullable) - Date when the rug was sold (null if not sold)
      - `is_available` (boolean) - Whether the rug is currently available for purchase
      - `created_at` (timestamptz) - Timestamp when the record was created
      - `updated_at` (timestamptz) - Timestamp when the record was last updated

  2. Security
    - Enable RLS on `Pre-made Rugs` table
    - Add policy for anyone to view available rugs (public read access)
    - Add policy for authenticated users to insert rugs
    - Add policy for authenticated users to update rugs
    - Add policy for authenticated users to delete rugs

  3. Triggers
    - Auto-update `updated_at` timestamp on record updates

  4. Notes
    - This is a duplicate of the "Pre-made Collection" table
    - Maintains identical structure and security policies
*/

-- Create the Pre-made Rugs table (duplicate of Pre-made Collection)
CREATE TABLE IF NOT EXISTS "Pre-made Rugs" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  image text,
  title text,
  description text,
  price numeric(10, 2) CHECK (price >= 0),
  stripe_price_id text,
  stripe_prod_id text,
  date_sold timestamptz,
  is_available boolean DEFAULT true,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE "Pre-made Rugs" ENABLE ROW LEVEL SECURITY;

-- Public can view all rugs
CREATE POLICY "Anyone can view rugs"
  ON "Pre-made Rugs"
  FOR SELECT
  TO public
  USING (true);

-- Authenticated users can insert rugs
CREATE POLICY "Authenticated users can insert rugs"
  ON "Pre-made Rugs"
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Authenticated users can update rugs
CREATE POLICY "Authenticated users can update rugs"
  ON "Pre-made Rugs"
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Authenticated users can delete rugs
CREATE POLICY "Authenticated users can delete rugs"
  ON "Pre-made Rugs"
  FOR DELETE
  TO authenticated
  USING (true);

-- Create trigger to automatically update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_premade_rugs_updated_at ON "Pre-made Rugs";
CREATE TRIGGER update_premade_rugs_updated_at
  BEFORE UPDATE ON "Pre-made Rugs"
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();